{{- if and (ne .Release.Namespace "default") .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: git-proxy
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: {{ .Release.Namespace }}
{{- end }}
